# Generated by Django 4.2.6 on 2023-11-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_dispatch_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней отправки'),
        ),
    ]
